name: Windows

on:
  push:
    branches:
      - master
      - ci/*
  pull_request:
    branches:
      - master

env:
  LLVM_MINGW_VERSION: 20250514
  VCPKG_COMMIT: 2ad004460f5db4d3b66f62f5799ff66c265c4b5d
  MELONDS_GIT_BRANCH: ${{ github.ref }}
  MELONDS_GIT_HASH: ${{ github.sha }}
  MELONDS_BUILD_PROVIDER: GitHub Actions
  MELONDS_VERSION_SUFFIX: " RC"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out sources
      uses: actions/checkout@v3
    - name: Fetch toolchain
      uses: robinraju/release-downloader@v1
      with:
        repository: mstorsjo/llvm-mingw
        tag: ${{ env.LLVM_MINGW_VERSION }}
        fileName: llvm-mingw-${{ env.LLVM_MINGW_VERSION }}-ucrt-x86_64.zip
        extract: true
    - name: Add toolchain to PATH
      run: Add-Content $Env:GITHUB_PATH "${Env:GITHUB_WORKSPACE}/llvm-mingw-${Env:LLVM_MINGW_VERSION}-ucrt-x86_64"
    - uses: lukka/get-cmake@latest
    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT }}
    - name: Configure
      run: |
        cmake --preset=release-mingw-x86_64 -DMELONDS_EMBED_BUILD_INFO=ON
    - name: Build
      run: cmake --build --preset=release-mingw-x86_64
    - uses: actions/upload-artifact@v4
      with:
        name: melonDS-windows-x86_64
        path: .\build\release-mingw-x86_64\melonDS.exe
