name: Windows

on:
  push:
    branches:
      - master
      - ci/*
  pull_request:
    branches:
      - master

env:
  MELONDS_GIT_BRANCH: ${{ github.ref }}
  MELONDS_GIT_HASH: ${{ github.sha }}
  MELONDS_BUILD_PROVIDER: GitHub Actions
#  MELONDS_VERSION_SUFFIX: " RC"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - name: x86_64
            os: windows-2025
          - name: arm64
            os: windows-11-arm
    
    runs-on: ${{ matrix.arch.os }}
    env:
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite
    steps:
    - name: Check out sources
      uses: actions/checkout@v3
    - name: Restore vcpkg cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/vcpkg_cache
        key: vcpkg-${{ matrix.arch.name }}-windows-${{ hashFiles('vcpkg.json') }}
        restore-keys: vcpkg-${{ matrix.arch.name }}-windows-
    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: vcpkg.json
    - name: Build
      uses: lukka/run-cmake@v10
      with:
        configurePreset: release-windows
        buildPreset: release-windows
        configurePresetAdditionalArgs: "['-DMELONDS_EMBED_BUILD_INFO=ON']"
    - uses: actions/upload-artifact@v4
      with:
        name: melonDS-windows-${{ matrix.arch.name }}
        path: .\build\release-windows\melonDS.exe
    - name: Save vcpkg cache
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/vcpkg_cache
        key: vcpkg-${{ matrix.arch.name }}-windows-${{ hashFiles('vcpkg.json') }}
