name: Windows

on:
  push:
    branches:
      - master
      - ci/*
  pull_request:
    branches:
      - master

env:
  VCPKG_COMMIT: 2ad004460f5db4d3b66f62f5799ff66c265c4b5d
  MELONDS_GIT_BRANCH: ${{ github.ref }}
  MELONDS_GIT_HASH: ${{ github.sha }}
  MELONDS_BUILD_PROVIDER: GitHub Actions
  MELONDS_VERSION_SUFFIX: " RC"

jobs:
  build:
    runs-on: windows-11-arm
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Check out sources
      uses: actions/checkout@v3
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: clangarm64
        update: true
        pacboy: toolchain:p cmake:p ninja:p make:p
    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT }}
    - name: Configure
      run: cmake --preset=release-mingw -DMELONDS_EMBED_BUILD_INFO=ON -DENABLE_JIT=OFF
    - name: Build
      run: cmake --build --preset=release-mingw
    - uses: actions/upload-artifact@v4
      with:
        name: melonDS-windows-arm64
        path: .\build\release-mingw\melonDS.exe
