name: Ubuntu

on:
  push:
    branches:
      - master
      - ci/vcpkg-update
      - ci/linux-vcpkg
  pull_request:
    branches:
      - master

env:
  MELONDS_GIT_BRANCH: ${{ github.ref }}
  MELONDS_GIT_HASH: ${{ github.sha }}
  MELONDS_BUILD_PROVIDER: GitHub Actions
  MELONDS_VERSION_SUFFIX: " RC"

jobs:
  build-ubuntu:
    strategy:
      matrix:
        arch:
          - name: x86_64
            runner: ubuntu-22.04

    name: ${{ matrix.arch.name }}
    runs-on: ${{ matrix.arch.runner }}
    steps:
      - name: Check out sources
        uses: actions/checkout@v3
      - name: Install dependencies for package building
        run: |
          sudo apt install cmake ninja-build g++ pkg-config bison flex autoconf automake libtool python3-jinja2 nasm \
            libx11-dev libxft-dev libxext-dev libwayland-dev libxkbcommon-dev libegl1-mesa-dev libibus-1.0-dev \
            '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libegl1-mesa-dev libcap-dev
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: b2cb0da531c2f1f740045bfe7c4dac59f0b2b69c
      - name: Build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: release-linux
          buildPreset: release-linux
          configurePresetAdditionalArgs: "['-DMELONDS_EMBED_BUILD_INFO=ON']"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{ matrix.arch.name }}
          path: build/release-linux/melonDS
