name: Windows

on:
  push:
    branches:
      - master
      - ci/*
  pull_request:
    branches:
      - master

env:
  VCPKG_COMMIT: b02e341c927f16d991edbd915d8ea43eac52096c
  MELONDS_GIT_BRANCH: ${{ github.ref }}
  MELONDS_GIT_HASH: ${{ github.sha }}
  MELONDS_BUILD_PROVIDER: GitHub Actions
  MELONDS_VERSION_SUFFIX: " RC"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out sources
      uses: actions/checkout@v3
    - name: Install toolchain
      shell: msys2bash.cmd
      run: pacman -S --noconfirm mingw-w64-ucrt-x86_64-toolchain
    - name: Set up CMake
      uses: lukka/get-cmake@v3.31.6
    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT }}
    - name: Configure
      env:
        MSYSTEM: UCRT64
        CC: C:\msys64\ucrt64\bin\gcc.exe
        CXX: C:\msys64\ucrt64\bin\g++.exe
      run: |
        cmake `
          --preset=release-mingw-x86_64 `
          -DMELONDS_EMBED_BUILD_INFO=ON 
    - name: Build
      run: cmake --build --preset=release-mingw-x86_64
    - uses: actions/upload-artifact@v4
      with:
        name: melonDS-windows-x86_64
        path: .\build\release-mingw-x86_64\melonDS.exe
