name: Windows

on:
  push:
    branches:
      - master
      - ci/*
  pull_request:
    branches:
      - master

env:
  MELONDS_GIT_BRANCH: ${{ github.ref }}
  MELONDS_GIT_HASH: ${{ github.sha }}
  MELONDS_BUILD_PROVIDER: GitHub Actions
#  MELONDS_VERSION_SUFFIX: " RC"

jobs:
  build:
    runs-on: windows-2025
    env:
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite
    steps:
    - name: Check out sources
      uses: actions/checkout@v3
    - name: Restore vcpkg cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/vcpkg_cache
        key: vcpkg-x86_64-windows-${{ hashFiles('vcpkg.json') }}
        restore-keys: vcpkg-x86_64-windows-
    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: vcpkg.json
    - name: Configure
      run: cmake --preset=release-windows -DMELONDS_EMBED_BUILD_INFO=ON
    - name: Build
      run: cmake --build --preset=release-windows
    - uses: actions/upload-artifact@v4
      with:
        name: melonDS-windows-x86_64
        path: .\build\release-windows\melonDS.exe
    - name: Save vcpkg cache
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/vcpkg_cache
        key: vcpkg-x86_64-windows-${{ hashFiles('vcpkg.json') }}
